import type { Listing, User, CommunityAnnouncement, CofounderRequest } from '@/types'
import type { AnalyticsOverview, ListingPerformance, DailyViewData } from '@/features/analytics/services/analytics-service'
import type { SovereignMember } from '@/features/community/services/community-service'

export const mockUser: User = {
  id: 'mock-user-001',
  email: 'demo@midway.dev',
  display_name: 'Demo User',
  avatar_url: null,
  created_at: '2024-01-01T00:00:00Z',
}

export const mockSovereignMembers: SovereignMember[] = [
  {
    id: 'sovereign-001',
    email: 'alex@startup.io',
    display_name: 'Alex Chen',
    avatar_url: null,
    joined_at: '2024-02-15T10:00:00Z',
  },
  {
    id: 'sovereign-002',
    email: 'maria@techventures.com',
    display_name: 'Maria Rodriguez',
    avatar_url: null,
    joined_at: '2024-02-20T14:30:00Z',
  },
  {
    id: 'sovereign-003',
    email: 'james@buildfaster.dev',
    display_name: 'James Wilson',
    avatar_url: null,
    joined_at: '2024-03-01T09:00:00Z',
  },
  {
    id: 'sovereign-004',
    email: 'sarah@indiemaker.co',
    display_name: 'Sarah Thompson',
    avatar_url: null,
    joined_at: '2024-03-10T16:45:00Z',
  },
]

export const mockAnnouncements: CommunityAnnouncement[] = [
  {
    id: 'ann-001',
    title: 'Welcome to the Sovereign Community!',
    content: 'Thank you for being one of our founding members. This exclusive space is where we share early updates, gather feedback, and build MIDWAY together. Your voice matters here.',
    author_id: 'admin-001',
    is_pinned: true,
    published_at: '2024-02-01T10:00:00Z',
    created_at: '2024-02-01T10:00:00Z',
    updated_at: '2024-02-01T10:00:00Z',
  },
  {
    id: 'ann-002',
    title: 'New Feature: Analytics Dashboard',
    content: 'Duke and Sovereign members now have access to detailed analytics. Track your listing views, see performance trends, and understand your audience better. Check it out in your dashboard!',
    author_id: 'admin-001',
    is_pinned: false,
    published_at: '2024-03-15T14:00:00Z',
    created_at: '2024-03-15T14:00:00Z',
    updated_at: '2024-03-15T14:00:00Z',
  },
  {
    id: 'ann-003',
    title: 'Co-founder Program Now Open',
    content: 'As a Sovereign member, you can now apply to become a co-founder of MIDWAY. Submit your partnership request through the dashboard. Looking forward to hearing your ideas!',
    author_id: 'admin-001',
    is_pinned: false,
    published_at: '2024-03-20T09:30:00Z',
    created_at: '2024-03-20T09:30:00Z',
    updated_at: '2024-03-20T09:30:00Z',
  },
]

export const mockCofounderRequests: (CofounderRequest & { user: User })[] = [
  {
    id: 'cfr-001',
    user_id: 'sovereign-001',
    status: 'pending',
    message: 'I have 10 years of experience building marketplaces. Led product at a YC startup. Would love to help scale MIDWAY and bring my network of indie developers.',
    admin_notes: null,
    reviewed_by: null,
    reviewed_at: null,
    created_at: '2024-03-18T10:00:00Z',
    updated_at: '2024-03-18T10:00:00Z',
    user: {
      id: 'sovereign-001',
      email: 'alex@startup.io',
      display_name: 'Alex Chen',
      avatar_url: null,
      created_at: '2024-02-15T10:00:00Z',
    },
  },
  {
    id: 'cfr-002',
    user_id: 'sovereign-002',
    status: 'in_discussion',
    message: 'Former engineer at Stripe. Passionate about helping creators monetize their work. I can help with payments infrastructure and growth strategies.',
    admin_notes: 'Great background, scheduled call for next week',
    reviewed_by: 'admin-001',
    reviewed_at: '2024-03-16T15:00:00Z',
    created_at: '2024-03-15T11:30:00Z',
    updated_at: '2024-03-16T15:00:00Z',
    user: {
      id: 'sovereign-002',
      email: 'maria@techventures.com',
      display_name: 'Maria Rodriguez',
      avatar_url: null,
      created_at: '2024-02-20T14:30:00Z',
    },
  },
]

export const mockAnalyticsOverview: AnalyticsOverview = {
  totalViews: 12847,
  totalListings: 8,
  totalPoints: 450,
  viewsToday: 127,
  viewsThisWeek: 892,
  viewsThisMonth: 3456,
}

export const mockListingPerformance: ListingPerformance[] = [
  { listingId: 'mock-001', listingTitle: 'SaaS Dashboard Starter Kit', views: 3240, uniqueViewers: 2180 },
  { listingId: 'mock-004', listingTitle: 'REST API Boilerplate', views: 2890, uniqueViewers: 1950 },
  { listingId: 'mock-006', listingTitle: 'AI Content Generator Tool', views: 2150, uniqueViewers: 1680 },
  { listingId: 'mock-014', listingTitle: 'Real-time Collaboration Whiteboard', views: 1820, uniqueViewers: 1340 },
  { listingId: 'mock-008', listingTitle: 'GraphQL API Gateway', views: 1540, uniqueViewers: 1120 },
  { listingId: 'mock-016', listingTitle: 'Webhook Management Service', views: 1207, uniqueViewers: 890 },
]

export const mockDailyViews: DailyViewData[] = (() => {
  const data: DailyViewData[] = []
  const now = new Date()
  for (let i = 30; i >= 0; i--) {
    const date = new Date(now)
    date.setDate(date.getDate() - i)
    const baseViews = Math.floor(Math.random() * 150) + 50
    data.push({
      date: date.toISOString().split('T')[0],
      views: baseViews + Math.floor(Math.random() * 50),
      uniqueViewers: Math.floor(baseViews * 0.7) + Math.floor(Math.random() * 30),
    })
  }
  return data
})()

export const mockListings: Listing[] = [
  {
    id: 'mock-001',
    title: 'SaaS Dashboard Starter Kit',
    description: 'Modern dashboard with analytics, user management, and billing integration. Built with Next.js 14, Tailwind, and Stripe.',
    category: 'webapp',
    tech_stack: ['Next.js', 'TypeScript', 'Tailwind CSS', 'Stripe', 'Prisma'],
    price: 2500,
    completion_percent: 75,
    repo_url: 'https://github.com/example/saas-dashboard',
    demo_url: 'https://demo.example.com',
    images: [],
    status: 'active',
    seller_id: 'mock-user-001',
    seller: mockUser,
    is_featured: true,
    featured_until: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: '2024-03-15T10:00:00Z',
    updated_at: '2024-03-15T10:00:00Z',
  },
  {
    id: 'mock-002',
    title: 'iOS Fitness Tracking App',
    description: 'SwiftUI fitness app with workout tracking, progress charts, and HealthKit integration. Core features complete.',
    category: 'mobile',
    tech_stack: ['Swift', 'SwiftUI', 'HealthKit', 'CoreData', 'Charts'],
    price: 4500,
    completion_percent: 60,
    repo_url: null,
    demo_url: null,
    images: [],
    status: 'active',
    seller_id: 'mock-user-001',
    seller: mockUser,
    is_featured: false,
    featured_until: null,
    created_at: '2024-03-10T14:30:00Z',
    updated_at: '2024-03-10T14:30:00Z',
  },
  {
    id: 'mock-003',
    title: '2D Platformer Game Engine',
    description: 'Unity-based platformer with level editor, character customization, and mod support. Includes 10 demo levels.',
    category: 'game',
    tech_stack: ['Unity', 'C#', 'DOTween', 'Addressables'],
    price: 3200,
    completion_percent: 45,
    repo_url: 'https://github.com/example/platformer-engine',
    demo_url: 'https://play.example.com/demo',
    images: [],
    status: 'active',
    seller_id: 'mock-user-001',
    seller: mockUser,
    is_featured: true,
    featured_until: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: '2024-03-08T09:15:00Z',
    updated_at: '2024-03-08T09:15:00Z',
  },
  {
    id: 'mock-004',
    title: 'REST API Boilerplate',
    description: 'Production-ready Node.js API with auth, rate limiting, logging, and OpenAPI docs. Docker-ready.',
    category: 'api',
    tech_stack: ['Node.js', 'Express', 'PostgreSQL', 'Redis', 'Docker'],
    price: 1200,
    completion_percent: 90,
    repo_url: 'https://github.com/example/api-boilerplate',
    demo_url: null,
    images: [],
    status: 'active',
    seller_id: 'mock-user-001',
    seller: mockUser,
    is_featured: false,
    featured_until: null,
    created_at: '2024-03-05T16:45:00Z',
    updated_at: '2024-03-05T16:45:00Z',
  },
  {
    id: 'mock-005',
    title: 'E-commerce React Native App',
    description: 'Cross-platform shopping app with cart, checkout, and payment integration. Missing push notifications.',
    category: 'mobile',
    tech_stack: ['React Native', 'Expo', 'Redux', 'Stripe', 'Firebase'],
    price: 5500,
    completion_percent: 70,
    repo_url: null,
    demo_url: null,
    images: [],
    status: 'active',
    seller_id: 'mock-user-001',
    seller: mockUser,
    is_featured: false,
    featured_until: null,
    created_at: '2024-03-01T11:20:00Z',
    updated_at: '2024-03-01T11:20:00Z',
  },
  {
    id: 'mock-006',
    title: 'AI Content Generator Tool',
    description: 'Web app for generating blog posts, social media content, and marketing copy using OpenAI API.',
    category: 'webapp',
    tech_stack: ['Next.js', 'OpenAI', 'Vercel AI SDK', 'Supabase', 'Tailwind'],
    price: 3800,
    completion_percent: 55,
    repo_url: 'https://github.com/example/ai-writer',
    demo_url: 'https://ai-writer.example.com',
    images: [],
    status: 'draft',
    seller_id: 'mock-user-001',
    seller: mockUser,
    is_featured: false,
    featured_until: null,
    created_at: '2024-02-28T08:00:00Z',
    updated_at: '2024-02-28T08:00:00Z',
  },
  {
    id: 'mock-007',
    title: 'Multiplayer Card Game',
    description: 'Browser-based card game with real-time multiplayer, matchmaking, and ranking system.',
    category: 'game',
    tech_stack: ['Phaser 3', 'Socket.io', 'Node.js', 'MongoDB'],
    price: 2800,
    completion_percent: 35,
    repo_url: null,
    demo_url: null,
    images: [],
    status: 'active',
    seller_id: 'mock-user-001',
    seller: mockUser,
    is_featured: false,
    featured_until: null,
    created_at: '2024-02-25T13:30:00Z',
    updated_at: '2024-02-25T13:30:00Z',
  },
  {
    id: 'mock-008',
    title: 'GraphQL API Gateway',
    description: 'Federated GraphQL gateway with schema stitching, caching, and authentication middleware.',
    category: 'api',
    tech_stack: ['Apollo Server', 'GraphQL', 'TypeScript', 'Redis', 'Kubernetes'],
    price: 1800,
    completion_percent: 80,
    repo_url: 'https://github.com/example/graphql-gateway',
    demo_url: null,
    images: [],
    status: 'active',
    seller_id: 'mock-user-001',
    seller: mockUser,
    is_featured: false,
    featured_until: null,
    created_at: '2024-02-20T10:00:00Z',
    updated_at: '2024-02-20T10:00:00Z',
  },
  {
    id: 'mock-009',
    title: 'CLI Task Manager',
    description: 'Terminal-based task management tool with Todoist sync, tags, and recurring tasks support.',
    category: 'other',
    tech_stack: ['Rust', 'SQLite', 'Clap', 'Tokio'],
    price: 800,
    completion_percent: 65,
    repo_url: 'https://github.com/example/task-cli',
    demo_url: null,
    images: [],
    status: 'active',
    seller_id: 'mock-user-001',
    seller: mockUser,
    is_featured: false,
    featured_until: null,
    created_at: '2024-02-15T15:45:00Z',
    updated_at: '2024-02-15T15:45:00Z',
  },
  {
    id: 'mock-010',
    title: 'Video Streaming Platform',
    description: 'Full-featured streaming site with HLS support, user channels, and monetization. Needs CDN setup.',
    category: 'webapp',
    tech_stack: ['Next.js', 'FFmpeg', 'AWS S3', 'HLS.js', 'PostgreSQL'],
    price: 8500,
    completion_percent: 50,
    repo_url: null,
    demo_url: null,
    images: [],
    status: 'sold',
    seller_id: 'mock-user-001',
    seller: mockUser,
    is_featured: false,
    featured_until: null,
    created_at: '2024-02-10T09:30:00Z',
    updated_at: '2024-02-10T09:30:00Z',
  },
  {
    id: 'mock-011',
    title: 'Social Media Analytics Dashboard',
    description: 'Track engagement, followers, and growth across multiple platforms. Includes automated reporting.',
    category: 'webapp',
    tech_stack: ['React', 'D3.js', 'Node.js', 'MongoDB', 'Twitter API'],
    price: 3200,
    completion_percent: 68,
    repo_url: 'https://github.com/example/social-analytics',
    demo_url: 'https://analytics.example.com',
    images: [],
    status: 'active',
    seller_id: 'mock-user-001',
    seller: mockUser,
    is_featured: false,
    featured_until: null,
    created_at: '2024-02-08T14:00:00Z',
    updated_at: '2024-02-08T14:00:00Z',
  },
  {
    id: 'mock-012',
    title: 'Inventory Management System',
    description: 'Track stock levels, orders, and suppliers. Includes barcode scanning and low-stock alerts.',
    category: 'webapp',
    tech_stack: ['Vue.js', 'Laravel', 'MySQL', 'Redis'],
    price: 4200,
    completion_percent: 82,
    repo_url: null,
    demo_url: null,
    images: [],
    status: 'active',
    seller_id: 'mock-user-001',
    seller: mockUser,
    is_featured: false,
    featured_until: null,
    created_at: '2024-02-05T11:30:00Z',
    updated_at: '2024-02-05T11:30:00Z',
  },
  {
    id: 'mock-013',
    title: 'Meditation & Wellness App',
    description: 'iOS app with guided meditations, breathing exercises, and sleep sounds. Missing subscription system.',
    category: 'mobile',
    tech_stack: ['Swift', 'SwiftUI', 'AVFoundation', 'CloudKit'],
    price: 3800,
    completion_percent: 55,
    repo_url: null,
    demo_url: null,
    images: [],
    status: 'active',
    seller_id: 'mock-user-001',
    seller: mockUser,
    is_featured: false,
    featured_until: null,
    created_at: '2024-02-03T09:00:00Z',
    updated_at: '2024-02-03T09:00:00Z',
  },
  {
    id: 'mock-014',
    title: 'Real-time Collaboration Whiteboard',
    description: 'Digital whiteboard with drawing tools, sticky notes, and real-time sync for remote teams.',
    category: 'webapp',
    tech_stack: ['Next.js', 'Canvas API', 'Socket.io', 'PostgreSQL'],
    price: 5200,
    completion_percent: 72,
    repo_url: 'https://github.com/example/collab-board',
    demo_url: 'https://board.example.com',
    images: [],
    status: 'active',
    seller_id: 'mock-user-001',
    seller: mockUser,
    is_featured: true,
    featured_until: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: '2024-01-30T16:00:00Z',
    updated_at: '2024-01-30T16:00:00Z',
  },
  {
    id: 'mock-015',
    title: 'Roguelike Dungeon Crawler',
    description: 'Pixel art roguelike with procedural dungeons, permadeath, and item crafting. 50+ enemy types.',
    category: 'game',
    tech_stack: ['Godot', 'GDScript', 'Aseprite'],
    price: 2400,
    completion_percent: 40,
    repo_url: null,
    demo_url: 'https://itch.io/example/dungeon',
    images: [],
    status: 'active',
    seller_id: 'mock-user-001',
    seller: mockUser,
    is_featured: false,
    featured_until: null,
    created_at: '2024-01-28T10:15:00Z',
    updated_at: '2024-01-28T10:15:00Z',
  },
  {
    id: 'mock-016',
    title: 'Webhook Management Service',
    description: 'API for managing, routing, and monitoring webhooks with retry logic and event logging.',
    category: 'api',
    tech_stack: ['Go', 'PostgreSQL', 'Redis', 'Docker', 'Prometheus'],
    price: 1500,
    completion_percent: 85,
    repo_url: 'https://github.com/example/webhook-hub',
    demo_url: null,
    images: [],
    status: 'active',
    seller_id: 'mock-user-001',
    seller: mockUser,
    is_featured: false,
    featured_until: null,
    created_at: '2024-01-25T13:45:00Z',
    updated_at: '2024-01-25T13:45:00Z',
  },
  {
    id: 'mock-017',
    title: 'Recipe Sharing Platform',
    description: 'Social platform for sharing recipes with meal planning, shopping lists, and nutrition info.',
    category: 'webapp',
    tech_stack: ['Next.js', 'Prisma', 'PostgreSQL', 'Cloudinary', 'Tailwind'],
    price: 2900,
    completion_percent: 63,
    repo_url: null,
    demo_url: 'https://recipes.example.com',
    images: [],
    status: 'active',
    seller_id: 'mock-user-001',
    seller: mockUser,
    is_featured: false,
    featured_until: null,
    created_at: '2024-01-22T08:30:00Z',
    updated_at: '2024-01-22T08:30:00Z',
  },
  {
    id: 'mock-018',
    title: 'Personal Finance Tracker',
    description: 'Android app for budgeting, expense tracking, and financial goals with bank sync support.',
    category: 'mobile',
    tech_stack: ['Kotlin', 'Jetpack Compose', 'Room', 'Plaid API'],
    price: 3500,
    completion_percent: 58,
    repo_url: null,
    demo_url: null,
    images: [],
    status: 'active',
    seller_id: 'mock-user-001',
    seller: mockUser,
    is_featured: false,
    featured_until: null,
    created_at: '2024-01-20T15:00:00Z',
    updated_at: '2024-01-20T15:00:00Z',
  },
  {
    id: 'mock-019',
    title: 'VSCode Extension for API Testing',
    description: 'Test REST and GraphQL APIs directly from VSCode with collections, environments, and mock servers.',
    category: 'other',
    tech_stack: ['TypeScript', 'VSCode API', 'Axios', 'GraphQL'],
    price: 950,
    completion_percent: 75,
    repo_url: 'https://github.com/example/vscode-api-tester',
    demo_url: null,
    images: [],
    status: 'active',
    seller_id: 'mock-user-001',
    seller: mockUser,
    is_featured: false,
    featured_until: null,
    created_at: '2024-01-18T11:20:00Z',
    updated_at: '2024-01-18T11:20:00Z',
  },
  {
    id: 'mock-020',
    title: 'Event Booking Platform',
    description: 'Full booking system with ticketing, seating charts, and payment processing for venues.',
    category: 'webapp',
    tech_stack: ['React', 'Node.js', 'Stripe', 'PostgreSQL', 'SendGrid'],
    price: 6200,
    completion_percent: 67,
    repo_url: null,
    demo_url: null,
    images: [],
    status: 'active',
    seller_id: 'mock-user-001',
    seller: mockUser,
    is_featured: false,
    featured_until: null,
    created_at: '2024-01-15T09:45:00Z',
    updated_at: '2024-01-15T09:45:00Z',
  },
  {
    id: 'mock-021',
    title: 'Tower Defense Game',
    description: 'Strategic tower defense with 30 tower types, upgrade paths, and endless mode. Needs balancing.',
    category: 'game',
    tech_stack: ['Unity', 'C#', 'Addressables', 'Unity Ads'],
    price: 2100,
    completion_percent: 52,
    repo_url: null,
    demo_url: 'https://play.example.com/tower-defense',
    images: [],
    status: 'active',
    seller_id: 'mock-user-001',
    seller: mockUser,
    is_featured: false,
    featured_until: null,
    created_at: '2024-01-12T14:30:00Z',
    updated_at: '2024-01-12T14:30:00Z',
  },
  {
    id: 'mock-022',
    title: 'Email Marketing Automation',
    description: 'Create campaigns, manage lists, and automate sequences with analytics and A/B testing.',
    category: 'api',
    tech_stack: ['Python', 'FastAPI', 'Celery', 'PostgreSQL', 'AWS SES'],
    price: 4800,
    completion_percent: 78,
    repo_url: 'https://github.com/example/email-automation',
    demo_url: null,
    images: [],
    status: 'active',
    seller_id: 'mock-user-001',
    seller: mockUser,
    is_featured: false,
    featured_until: null,
    created_at: '2024-01-10T10:00:00Z',
    updated_at: '2024-01-10T10:00:00Z',
  },
  {
    id: 'mock-023',
    title: 'Language Learning App',
    description: 'Flutter app with spaced repetition, speech recognition, and gamified lessons for 10 languages.',
    category: 'mobile',
    tech_stack: ['Flutter', 'Dart', 'Firebase', 'Google Cloud Speech'],
    price: 7500,
    completion_percent: 45,
    repo_url: null,
    demo_url: null,
    images: [],
    status: 'active',
    seller_id: 'mock-user-001',
    seller: mockUser,
    is_featured: false,
    featured_until: null,
    created_at: '2024-01-08T16:15:00Z',
    updated_at: '2024-01-08T16:15:00Z',
  },
  {
    id: 'mock-024',
    title: 'Code Snippet Manager',
    description: 'Desktop app for organizing code snippets with syntax highlighting, tags, and cloud sync.',
    category: 'other',
    tech_stack: ['Electron', 'React', 'Monaco Editor', 'SQLite'],
    price: 1100,
    completion_percent: 88,
    repo_url: 'https://github.com/example/snippet-manager',
    demo_url: null,
    images: [],
    status: 'active',
    seller_id: 'mock-user-001',
    seller: mockUser,
    is_featured: false,
    featured_until: null,
    created_at: '2024-01-05T12:00:00Z',
    updated_at: '2024-01-05T12:00:00Z',
  },
  {
    id: 'mock-025',
    title: 'Job Board Platform',
    description: 'Full-featured job board with company profiles, applicant tracking, and resume parsing.',
    category: 'webapp',
    tech_stack: ['Next.js', 'Prisma', 'PostgreSQL', 'Algolia', 'Stripe'],
    price: 5800,
    completion_percent: 71,
    repo_url: null,
    demo_url: 'https://jobs.example.com',
    images: [],
    status: 'active',
    seller_id: 'mock-user-001',
    seller: mockUser,
    is_featured: false,
    featured_until: null,
    created_at: '2024-01-03T08:00:00Z',
    updated_at: '2024-01-03T08:00:00Z',
  },
  {
    id: 'mock-026',
    title: 'Puzzle Match-3 Game',
    description: 'Casual match-3 game with 200+ levels, power-ups, and daily challenges. Ready for monetization.',
    category: 'game',
    tech_stack: ['Unity', 'C#', 'Unity IAP', 'Firebase Analytics'],
    price: 3300,
    completion_percent: 92,
    repo_url: null,
    demo_url: null,
    images: [],
    status: 'active',
    seller_id: 'mock-user-001',
    seller: mockUser,
    is_featured: false,
    featured_until: null,
    created_at: '2024-01-01T10:30:00Z',
    updated_at: '2024-01-01T10:30:00Z',
  },
]

export const USE_MOCK_DATA = process.env.NODE_ENV === 'development'
